### ISSUE TITLE
Update outstanding supply at reserve.mento.org to account for Mobius pool

### ISSUE THREAD

**Issue by ole-nov** [mento-protocol/reserve-site#11]
Description:

The outstanding supply of cUSD on the reserve website shows more token than actually exists. This is because the liquidity in the Mento 1:1 Mobius pool is owned by the protocol. 

From the reserve perspective, the cUSD in the Mobius pool doesn't exist. Only when user makes a swap and adds USDCet to the pool, it is 'minted'. 

Which means, we should subtract it from outstanding supply of cUSD.
Mento 1:1 Mobius pool: https://www.mobius.money/pool/0xfa3df877f98ac5ecd87456a7accaa948462412f0

Acceptance criteria: 

- The outstanding supply of cUSD on reserve.mento.org dynamically subtracts the amount of cUSD in Mento 1:1 Mobius pool.

**Comment by bayological** [comment]
👉 [Pull request](https://github.com/mento-protocol/reserve-site/pull/12)
