### ISSUE TITLE
BUG: Reserve site displays 0% for Eth reserve holdings and some target allocations

### ISSUE THREAD

**Issue by bayological** [mento-protocol/reserve-site#15]
#### **Description**
When loading the reserve website the target allocation for ETH, BTC & cMC02 shows up as 0%. After refreshing the page the correct percentage is displayed.

#### **Steps To Reproduce**
It's not possible to reproduce the issue, it happens intermittently. The occurrence at the time of creating this issue was 2022-11-17 09-33-41 EST (maybe logs can be checked). 

#### **Screenshots**
![Screenshot from 2022-11-17 09-33-41](https://user-images.githubusercontent.com/6872903/202474796-b34bbd41-8bf9-482d-9b2e-60fa6579272c.png)

**Comment by ole-nov** [comment]
Current composition is affected as well. Right now the webpage shows 0% in Eth holdings.

**Comment by bayological** [comment]
This is still unresolved. We should look into adding retries to the calls that fetch the eth balance in holdings.ts & clean up sentry events (disable auto reporting, manually report API errors)
