### ISSUE TITLE
Outstanding supply should take into account the cUSD held in the reserve multisig

### ISSUE THREAD

**Issue by bayological** [mento-protocol/reserve-site#28]
**Description**
The total outstanding supply of cUSD that is displayed on the site needs to take into account any cUSD held by the reserve multisig. This was done previously but should be double-checked to ensure the numbers are correct. 

Previous PR:
https://github.com/mento-protocol/reserve-site/pull/24

**Acceptance Criteria**

- [x] The outstanding supply of cUSD displayed on the site does not include the cUSD balance of the reserve multisig

**Comment by philbow61** [comment]
![Image](https://user-images.githubusercontent.com/80156619/234814165-e266525f-ea3b-4e54-8d0c-d2f5c053aa1e.png)



![Image](https://user-images.githubusercontent.com/80156619/234814043-3016690f-c379-44a4-bd36-7681dae1d199.png)



![Image](https://user-images.githubusercontent.com/80156619/234814327-8ac8bfc4-b471-48d9-901d-f632b04a23f1.png)


![Image](https://user-images.githubusercontent.com/80156619/234814506-5b21dc44-1644-402b-a6a4-819329365c22.png)

### 30.994.493,52 - 30.414.553,93 = 579.939,59 which is the amount in the reserve multisig


![Image](https://user-images.githubusercontent.com/80156619/234815390-54b80db4-383e-4029-9d5c-117b91eb1a5d.png)
