### ISSUE TITLE
Reserve website potential bugs

### ISSUE THREAD

**Issue by bowd** [mento-protocol/reserve-site#39]
**Description**

Roman brought up two potential reserve website issues:

1. I think we are not tracking the CELO and axlUSDC amounts in the partial reserve proxy as part of the reserve funds on reserve.mento.org right now. Could you create a ticket to fix this?
2. Relatedly, we are aiming to move more funds over from Anchorage to our Reserve Safe Multisig on Ethereum so save some custody costs for the reserve. Could we make sure that ETH, WETH (the native, staked ETH), USDC and WBTC of that address (0xd0697f70E79476195B742d5aFAb14BE50f98CC1E) are counted towards reserve collateral on the homepage as well?

For (1) it might be a mistake on his side he told us "Oh wait, we might actually track this already if I got my math right - could someone check to make sure?"  

For (2) I can't find any reference of `0xd0697f70E79476195B742d5aFAb14BE50f98CC1E` in the reserve website.

**Acceptance criteria**

- [ ] (1) is verified
- [ ] We start tracking all things in 0xd0697f70E79476195B742d5aFAb14BE50f98CC1E

**Comment by denviljclarke** [comment]
Point 1

@bowd, I confirmed that we are tracking partial reserve axlUSDC & CELO balances on the reserve website.

I removed addition of the partial reserve axlUSDC balance from the total USDC calculation and verified that that difference between the total before it was removed and total after it was removed is equal to the partial reserve axlUSDC balance

Similarly I removed the addition of the partial reserve CELO from the total Celo calculation and confirmed that the difference between the total CELO displayed on the live site and the total after the reserve addition is equal to the partial reserve CELO balance

Point 2  

Provisions have been made to add the safe address, however there are some we need to decide how we’ll display the balances, ETH will be displayed under ETH by default, as for WBTC & WETH, should those balances be displayed under BTC & ETH respectively, or should they be displayed under a separate heading, similar to this? 

<img width="382" alt="Screenshot 2023-06-24 at 11 53 32 AM" src="https://github.com/mento-protocol/reserve-site/assets/60730266/4c64f89f-1b4f-44a3-a7cc-c4e3aab1fc10">

**Comment by rcroessmann** [comment]
Let's for now NOT differentiate between bridged/wrapped versions and the original assets on the reserve homepage to keep things simple.

**Comment by denviljclarke** [comment]
> Let's for now NOT differentiate between bridged/wrapped versions and the original assets on the reserve homepage to keep things simple.

Okay, got it. Thanks! @rcroessmann
