### ISSUE TITLE
Alerting when reserve on celo runs low

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/reserve-site#48]
*Description*
We have[ Reserve](https://explorer.celo.org/mainnet/address/0x9380fA34Fd9e4Fd14c06305fd7B6199089eD4eb9) smart contract on Celo that is being manually refilled whenever it runs low on axlUSDC/axlEURO
Atm we rely one someone from the team checking either on the dashboard, or through celoscan how much of axlUSDC and axlEUROC we have in the reserve and wether we should refill it. It happened couple of times, that we noticed that we low on funds when there already was 0 of axlEUROC/axlUSDC in partial reserve.
This issue is about creating an alert system that will notify relevant team members that partial reserve needs to be refilled.

How implementation should look like: whenever the balance of axlUSDC or axlEUROC in the Reserve smart contract is low than the threshold set in the config, the bot should send a message to #protocol-operations channel on Mento Discord server, tagging @everyone with message like:
"The balance of axlEUROC in the Reserve is XXX. Make sure to refill it on time".

We should be able to configure several alerts. E.g when balance is at 200k, 50k, 5k.

*Acceptance criteria* 
We recieve notifications in #protocol-operations Discord channel whenever the reserve needs to be refilled with axlUSDC or axlEUROC

**Comment by bayological** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/rIS7CU7KkE/estimate/5) in Sprint Poker #​​25

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by bayological** [comment]
@olenovyk Do we still want to do this for the main reserve instead?

**Comment by olenovyk** [comment]
> @olenovyk Do we still want to do this for the main reserve instead?

Yes please. I will update an issue.
