### ISSUE TITLE
Privacy page formatting

### ISSUE THREAD

**Issue by bayological** [mento-protocol/reserve-site#90]
**Description**

The existing reserve site had a privacy page, which was left out of the rebrand design. We need to update the privacy page so its styling aligns with the new branding and ensure the privacy policy content is updated. Thre are no designs for this so simply ensuring fonts, spacing, line heights etc are in line with the rest of the site is fint.

We also should add a link to allow the privacy policy to be downloadable in PDF format.

The new privacy notice can be found [here](https://docs.google.com/document/d/1XlWHR7r2L3QoEbC_dBeYDCuyC8lt0YZ3/edit?usp=drive_link&ouid=115461431738185451043&rtpof=true&sd=true).

**Acceptance Criteria**

- [ ] The styling of the privacy page is in line with the updated branding
- [ ] The contents of the privacy page has been updated to match the new Mento Foundation privacy notice
- [ ] A PDF version of the privacy policy is downloadable via a clickable link under the title

**Comment by chapati23** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/reserve-site/90?planning-poker) with Zenhub @baroooo

**Comment by olenovyk** [comment]
Hey,
This will be a privacy page for all apps on mento.org subdomain, not just reserve, correct?

**Comment by bayological** [comment]
> Hey, This will be a privacy page for all apps on mento.org subdomain, not just reserve, correct?

This is just for the reserve redesign. It was left out of the design so it doesn't look right now.
